name: sunray_news
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # networking
  dio: ^5.0.2

  # pattern
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2

  # utils
  flutter_screenutil: ^5.7.0
  equatable: ^2.0.5
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.10
  pretty_dio_logger: ^1.3.1
  tabler_icons: ^2.5.0+1
  cupertino_icons: ^1.0.2
  splash_view: ^2.0.1

    

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Thin.ttf
          weight: 400
        - asset: assets/fonts/Lato/Lato-Light.ttf
          weight: 500
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 600
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700

